apiDebug: false
password: '1234'
timeout: 600000
contractsPath: ./contracts/

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: 'http://localhost:9000'
    stratoUrl: 'http://localhost/strato-api'
    blocUrl: 'http://localhost/bloc/v2.2'
    searchUrl: 'http://localhost/cirrus'
